// TODO: Remove this file once endpoint or mock server is established
import { AmountOption, EditDraftRequest, RequestStatus, ReviewType } from "./shared/types/request-type";
import { ApprovalComment } from "./shared/types/approval-type";

// export const mockRequests: ApprovalRequest[] = [
//   {
//     id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567801',
//     controlNumber: 'REQ-2025-001',
//     vendor: 'Acme Supplies Co.',
//     subject: 'Office Furniture Procurement',
//     status: RequestStatus.UnderReview,
//     currentStep: 'Department Head Approval',
//     createdOn: '2025-03-01',
//     lastUpdatedOn: '2025-03-05',
//     reviewType: ReviewType.Contract,
//     funds: [
//       { id: 1, name: 'furniture', amount: 234 },
//       { id: 2, name: 'office', amount: 512 },
//     ],
//     transactionType: 'Purchase Order',
//     amount: 150000,
//   },
//   {
//     id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567802',
//     controlNumber: 'REQ-2025-002',
//     vendor: 'TechZone Philippines',
//     subject: 'Laptop Replacement — IT Team',
//     status: RequestStatus.UnderReview,
//     currentStep: 'Budget Review',
//     createdOn: '2025-03-08',
//     lastUpdatedOn: '2025-03-09',
//     reviewType: ReviewType.Proposal,
//     funds: [
//       { id: 3, name: 'it', amount: 1243 },
//       { id: 4, name: 'hardware', amount: 891 },
//     ],
//     transactionType: 'Purchase Order',
//     amount: 320000,
//   },
//   {
//     id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567803',
//     controlNumber: 'REQ-2025-003',
//     vendor: 'CleanPro Services',
//     subject: 'Monthly Janitorial Contract Renewal',
//     status: RequestStatus.UnderReview,
//     currentStep: 'Finance Approval',
//     createdOn: '2025-03-10',
//     lastUpdatedOn: '2025-03-12',
//     reviewType: ReviewType.Proposal,
//     funds: [
//       { id: 5, name: 'facilities', amount: 678 },
//       { id: 6, name: 'contract', amount: 1000 },
//     ],
//     transactionType: 'Service Contract',
//     amount: 45000,
//   },
//   {
//     id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567804',
//     controlNumber: 'REQ-2025-004',
//     vendor: 'FastPrint Solutions',
//     subject: 'Printing Supplies — Q2 Stock',
//     status: RequestStatus.Draft,
//     currentStep: 'Department Head Approval',
//     createdOn: '2025-03-15',
//     lastUpdatedOn: '2025-03-15',
//     reviewType: ReviewType.Proposal,
//     funds: [
//       { id: 7, name: 'supplies', amount: 445 },
//       { id: 8, name: 'printing', amount: 187 },
//     ],
//     transactionType: 'Purchase Order',
//     amount: 18500,
//   },
//   {
//     id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567805',
//     controlNumber: 'REQ-2025-005',
//     vendor: 'GreenLeaf Catering',
//     subject: 'Annual Company Outing Catering',
//     status: RequestStatus.UnderReview,
//     currentStep: 'VP Operations Approval',
//     createdOn: '2025-03-18',
//     lastUpdatedOn: '2025-03-20',
//     reviewType: ReviewType.Contract,
//     funds: [
//       { id: 9, name: 'events', amount: 356 },
//       { id: 10, name: 'catering', amount: 123 },
//     ],
//     transactionType: 'Service Contract',
//     amount: 280000,
//   },
//   {
//     id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567806',
//     controlNumber: 'REQ-2025-006',
//     vendor: 'SafeGuard Security Inc.',
//     subject: 'CCTV System Upgrade — Main Office',
//     status: RequestStatus.Draft,
//     currentStep: 'Requestor Review',
//     createdOn: '2025-03-20',
//     lastUpdatedOn: '2025-03-20',
//     reviewType: ReviewType.Proposal,
//     funds: [
//       { id: 11, name: 'security', amount: 654 },
//       { id: 3, name: 'it', amount: 1243 },
//       { id: 12, name: 'infrastructure', amount: 923 },
//     ],
//     transactionType: 'Purchase Order',
//     amount: 95000,
//   },
//   {
//     id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567807',
//     controlNumber: 'REQ-2025-007',
//     vendor: 'MediCare Supplies PH',
//     subject: 'First Aid Kit Restocking — All Floors',
//     status: RequestStatus.Completed,
//     currentStep: 'Released',
//     createdOn: '2025-03-21',
//     lastUpdatedOn: '2025-03-28',
//     reviewType: ReviewType.Proposal,
//     funds: [
//       { id: 13, name: 'health', amount: 312 },
//       { id: 14, name: 'safety', amount: 267 },
//       { id: 7, name: 'supplies', amount: 445 },
//     ],
//     transactionType: 'Purchase Order',
//     amount: 12000,
//   },
//   {
//     id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567808',
//     controlNumber: 'REQ-2025-008',
//     vendor: 'SwiftCourier Logistics',
//     subject: 'Courier Service Contract — Q2',
//     status: RequestStatus.Rejected,
//     currentStep: 'Budget Review',
//     createdOn: '2025-03-22',
//     lastUpdatedOn: '2025-03-25',
//     reviewType: ReviewType.Proposal,
//     funds: [
//       { id: 15, name: 'logistics', amount: 445 },
//       { id: 6, name: 'contract', amount: 1000 },
//     ],
//     transactionType: 'Service Contract',
//     amount: 36000,
//   },
//   {
//     id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567809',
//     controlNumber: 'REQ-2025-009',
//     vendor: 'PowerSource Electrical',
//     subject: 'UPS Unit Replacement — Server Room',
//     status: RequestStatus.UnderReview,
//     currentStep: 'Finance Approval',
//     createdOn: '2025-03-23',
//     lastUpdatedOn: '2025-03-26',
//     reviewType: ReviewType.Proposal,
//     funds: [
//       { id: 3, name: 'it', amount: 1243 },
//       { id: 12, name: 'infrastructure', amount: 923 },
//       { id: 4, name: 'hardware', amount: 891 },
//     ],
//     transactionType: 'Purchase Order',
//     amount: 75000,
//   },
//   {
//     id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567810',
//     controlNumber: 'REQ-2025-010',
//     vendor: 'UrbanFurniture PH',
//     subject: 'Ergonomic Chairs — HR Department',
//     status: RequestStatus.Returned,
//     currentStep: 'Requestor Review',
//     createdOn: '2025-03-24',
//     lastUpdatedOn: '2025-03-27',
//     reviewType: ReviewType.Contract,
//     funds: [
//       { id: 1, name: 'furniture', amount: 234 },
//       { id: 17, name: 'hr', amount: 789 },
//     ],
//     transactionType: 'Purchase Order',
//     amount: 64000,
//   },
//   {
//     id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567811',
//     controlNumber: 'REQ-2025-011',
//     vendor: 'AquaFlow Solutions',
//     subject: 'Water Dispenser Maintenance Contract',
//     status: RequestStatus.Completed,
//     currentStep: 'Released',
//     createdOn: '2025-03-25',
//     lastUpdatedOn: '2025-04-01',
//     reviewType: ReviewType.Proposal,
//     funds: [
//       { id: 5, name: 'facilities', amount: 678 },
//       { id: 16, name: 'maintenance', amount: 834 },
//     ],
//     transactionType: 'Service Contract',
//     amount: 24000,
//   },
//   {
//     id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567812',
//     controlNumber: 'REQ-2025-012',
//     vendor: 'BrightMark Advertising',
//     subject: 'Tarpaulin Printing — Company Anniversary',
//     status: RequestStatus.Cancelled,
//     currentStep: 'Cancelled',
//     createdOn: '2025-03-26',
//     lastUpdatedOn: '2025-03-27',
//     reviewType: ReviewType.Others,
//     funds: [
//       { id: 18, name: 'marketing', amount: 312 },
//       { id: 9, name: 'events', amount: 356 },
//     ],
//     transactionType: 'Purchase Order',
//     amount: 8500,
//   },
//   {
//     id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567813',
//     controlNumber: 'REQ-2025-013',
//     vendor: 'NetConnect ISP',
//     subject: 'Fiber Internet Upgrade — Branch Office',
//     status: RequestStatus.UnderReview,
//     currentStep: 'VP Operations Approval',
//     createdOn: '2025-03-27',
//     lastUpdatedOn: '2025-03-30',
//     reviewType: ReviewType.Proposal,
//     funds: [
//       { id: 3, name: 'it', amount: 1243 },
//       { id: 12, name: 'infrastructure', amount: 923 },
//       { id: 21, name: 'network', amount: 567 },
//     ],
//     transactionType: 'Service Contract',
//     amount: 120000,
//   },
//   {
//     id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567814',
//     controlNumber: 'REQ-2025-014',
//     vendor: 'ElitePrint Digital',
//     subject: 'ID Card Printing — New Hires Batch 1',
//     status: RequestStatus.Completed,
//     currentStep: 'Released',
//     createdOn: '2025-03-28',
//     lastUpdatedOn: '2025-04-03',
//     reviewType: ReviewType.Contract,
//     funds: [
//       { id: 17, name: 'hr', amount: 789 },
//       { id: 6, name: 'Contract', amount: 234 },
//     ],
//     transactionType: 'Purchase Order',
//     amount: 5500,
//   },
//   {
//     id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567815',
//     controlNumber: 'REQ-2025-015',
//     vendor: 'TechZone Philippines',
//     subject: 'Network Switch Replacement — Floor 3',
//     status: RequestStatus.Draft,
//     currentStep: 'Requestor Review',
//     createdOn: '2025-03-29',
//     lastUpdatedOn: '2025-03-29',
//     reviewType: ReviewType.Proposal,
//     funds: [
//       { id: 3, name: 'it', amount: 1243 },
//       { id: 21, name: 'network', amount: 567 },
//       { id: 4, name: 'hardware', amount: 891 },
//     ],
//     transactionType: 'Purchase Order',
//     amount: 48000,
//   },
//   {
//     id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567816',
//     controlNumber: 'REQ-2025-016',
//     vendor: 'PrimeChem Janitorial',
//     subject: 'Cleaning Supplies — Monthly Replenishment',
//     status: RequestStatus.UnderReview,
//     currentStep: 'Department Head Approval',
//     createdOn: '2025-03-30',
//     lastUpdatedOn: '2025-04-01',
//     reviewType: ReviewType.Proposal,
//     funds: [
//       { id: 5, name: 'facilities', amount: 678 },
//       { id: 7, name: 'supplies', amount: 445 },
//     ],
//     transactionType: 'Purchase Order',
//     amount: 9800,
//   },
//   {
//     id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567817',
//     controlNumber: 'REQ-2025-017',
//     vendor: 'SolarTech Energy PH',
//     subject: 'Solar Panel Installation — Rooftop',
//     status: RequestStatus.Returned,
//     currentStep: 'Requestor Review',
//     createdOn: '2025-04-01',
//     lastUpdatedOn: '2025-04-04',
//     reviewType: ReviewType.Contract,
//     funds: [
//       { id: 5, name: 'facilities', amount: 678 },
//       { id: 12, name: 'infrastructure', amount: 923 },
//       { id: 22, name: 'energy', amount: 178 },
//     ],
//     transactionType: 'Purchase Order',
//     amount: 850000,
//   },
//   {
//     id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567818',
//     controlNumber: 'REQ-2025-018',
//     vendor: 'OfficeWorld Stationery',
//     subject: 'Stationery and Bond Paper — Q2 Stock',
//     status: RequestStatus.Rejected,
//     currentStep: 'Finance Approval',
//     createdOn: '2025-04-02',
//     lastUpdatedOn: '2025-04-05',
//     reviewType: ReviewType.Proposal,
//     funds: [
//       { id: 7, name: 'supplies', amount: 445 },
//       { id: 2, name: 'office', amount: 512 },
//     ],
//     transactionType: 'Purchase Order',
//     amount: 14200,
//   },
//   {
//     id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567819',
//     controlNumber: 'REQ-2025-019',
//     vendor: 'CoolBreeze HVAC Services',
//     subject: 'Aircon Preventive Maintenance — All Units',
//     status: RequestStatus.UnderReview,
//     currentStep: 'Budget Review',
//     createdOn: '2025-04-03',
//     lastUpdatedOn: '2025-04-06',
//     reviewType: ReviewType.Proposal,
//     funds: [
//       { id: 5, name: 'facilities', amount: 678 },
//       { id: 16, name: 'maintenance', amount: 834 },
//     ],
//     transactionType: 'Service Contract',
//     amount: 58000,
//   },
//   {
//     id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567820',
//     controlNumber: 'REQ-2025-020',
//     vendor: 'SafeVault Document Storage',
//     subject: 'Offsite Document Archiving — FY2024 Records',
//     status: RequestStatus.Draft,
//     currentStep: 'Requestor Review',
//     createdOn: '2025-04-05',
//     lastUpdatedOn: '2025-04-05',
//     reviewType: ReviewType.Others,
//     funds: [
//       { id: 19, name: 'compliance', amount: 567 },
//       { id: 20, name: 'records', amount: 423 },
//     ],
//     transactionType: 'Service Contract',
//     amount: 32000,
//   },
//   {
//     id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567821',
//     controlNumber: 'REQ-2025-021',
//     vendor: 'ProHealth Medical Supplies',
//     subject: 'Annual Medical Exam — All Employees',
//     status: RequestStatus.UnderReview,
//     currentStep: 'HR Approval',
//     createdOn: '2025-04-06',
//     lastUpdatedOn: '2025-04-07',
//     reviewType: ReviewType.Proposal,
//     funds: [
//       { id: 13, name: 'health', amount: 312 },
//       { id: 17, name: 'hr', amount: 789 },
//       { id: 19, name: 'compliance', amount: 567 },
//     ],
//     transactionType: 'Service Contract',
//     amount: 175000,
//   },
//   {
//     id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567822',
//     controlNumber: 'REQ-2025-022',
//     vendor: 'GlobalTravel Solutions',
//     subject: 'Business Travel Arrangements — Q2 Conferences',
//     status: RequestStatus.Rejected,
//     currentStep: 'VP Finance Approval',
//     createdOn: '2025-04-07',
//     lastUpdatedOn: '2025-04-09',
//     reviewType: ReviewType.Others,
//     funds: [
//       { id: 23, name: 'travel', amount: 145 },
//       { id: 9, name: 'events', amount: 356 },
//     ],
//     transactionType: 'Service Contract',
//     amount: 220000,
//   },
//   {
//     id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567823',
//     controlNumber: 'REQ-2025-023',
//     vendor: 'SwiftCourier Logistics',
//     subject: 'Express Delivery Service — Legal Documents',
//     status: RequestStatus.Completed,
//     currentStep: 'Released',
//     createdOn: '2025-04-08',
//     lastUpdatedOn: '2025-04-10',
//     reviewType: ReviewType.Others,
//     funds: [
//       { id: 15, name: 'logistics', amount: 445 },
//       { id: 24, name: 'legal', amount: 89 },
//     ],
//     transactionType: 'Service Contract',
//     amount: 4500,
//   },
//   {
//     id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567824',
//     controlNumber: 'REQ-2025-024',
//     vendor: 'TechZone Philippines',
//     subject: 'Monitor Replacement — Finance Department',
//     status: RequestStatus.UnderReview,
//     currentStep: 'Budget Review',
//     createdOn: '2025-04-09',
//     lastUpdatedOn: '2025-04-11',
//     reviewType: ReviewType.Proposal,
//     funds: [
//       { id: 3, name: 'it', amount: 1243 },
//       { id: 4, name: 'hardware', amount: 891 },
//     ],
//     transactionType: 'Purchase Order',
//     amount: 86000,
//   },
//   {
//     id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567825',
//     controlNumber: 'REQ-2025-025',
//     vendor: 'BrightSpark Electrical',
//     subject: 'Emergency Generator Maintenance',
//     status: RequestStatus.Draft,
//     currentStep: 'Requestor Review',
//     createdOn: '2025-04-10',
//     lastUpdatedOn: '2025-04-10',
//     reviewType: ReviewType.Proposal,
//     funds: [
//       { id: 5, name: 'facilities', amount: 678 },
//       { id: 16, name: 'maintenance', amount: 834 },
//       { id: 12, name: 'infrastructure', amount: 923 },
//     ],
//     transactionType: 'Service Contract',
//     amount: 42000,
//   },
//   {
//     id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567826',
//     controlNumber: 'REQ-2025-026',
//     vendor: 'Acme Supplies Co.',
//     subject: 'Whiteboard and Markers — Training Room',
//     status: RequestStatus.Cancelled,
//     currentStep: 'Cancelled',
//     createdOn: '2025-04-11',
//     lastUpdatedOn: '2025-04-12',
//     reviewType: ReviewType.Contract,
//     funds: [
//       { id: 7, name: 'supplies', amount: 445 },
//       { id: 27, name: 'training', amount: 167 },
//     ],
//     transactionType: 'Purchase Order',
//     amount: 7200,
//   },
//   {
//     id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567827',
//     controlNumber: 'REQ-2025-027',
//     vendor: 'SecureNet IT Services',
//     subject: 'Firewall License Renewal — HQ',
//     status: RequestStatus.UnderReview,
//     currentStep: 'IT Manager Approval',
//     createdOn: '2025-04-12',
//     lastUpdatedOn: '2025-04-14',
//     reviewType: ReviewType.Proposal,
//     funds: [
//       { id: 3, name: 'it', amount: 1243 },
//       { id: 11, name: 'security', amount: 654 },
//       { id: 25, name: 'license', amount: 245 },
//     ],
//     transactionType: 'Service Contract',
//     amount: 98000,
//   },
//   {
//     id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567828',
//     controlNumber: 'REQ-2025-028',
//     vendor: 'UrbanFurniture PH',
//     subject: 'Reception Area Sofa Set Replacement',
//     status: RequestStatus.Returned,
//     currentStep: 'Requestor Review',
//     createdOn: '2025-04-13',
//     lastUpdatedOn: '2025-04-15',
//     reviewType: ReviewType.Proposal,
//     funds: [
//       { id: 1, name: 'furniture', amount: 234 },
//       { id: 5, name: 'facilities', amount: 678 },
//     ],
//     transactionType: 'Purchase Order',
//     amount: 55000,
//   },
//   {
//     id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567829',
//     controlNumber: 'REQ-2025-029',
//     vendor: 'GreenLeaf Catering',
//     subject: 'Board Meeting Catering — April Sessions',
//     status: RequestStatus.Completed,
//     currentStep: 'Released',
//     createdOn: '2025-04-14',
//     lastUpdatedOn: '2025-04-16',
//     reviewType: ReviewType.Others,
//     funds: [
//       { id: 10, name: 'catering', amount: 123 },
//       { id: 9, name: 'events', amount: 356 },
//     ],
//     transactionType: 'Service Contract',
//     amount: 18000,
//   },
//   {
//     id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567830',
//     controlNumber: 'REQ-2025-030',
//     vendor: 'CleanPro Services',
//     subject: 'Deep Cleaning Service — Warehouse',
//     status: RequestStatus.UnderReview,
//     currentStep: 'Operations Approval',
//     createdOn: '2025-04-15',
//     lastUpdatedOn: '2025-04-17',
//     reviewType: ReviewType.Proposal,
//     funds: [
//       { id: 5, name: 'facilities', amount: 678 },
//       { id: 16, name: 'maintenance', amount: 834 },
//     ],
//     transactionType: 'Service Contract',
//     amount: 28000,
//   },
//   {
//     id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567831',
//     controlNumber: 'REQ-2025-031',
//     vendor: 'NetConnect ISP',
//     subject: 'Wi-Fi Access Point Installation — Floor 4',
//     status: RequestStatus.Draft,
//     currentStep: 'Requestor Review',
//     createdOn: '2025-04-16',
//     lastUpdatedOn: '2025-04-16',
//     reviewType: ReviewType.Contract,
//     funds: [
//       { id: 3, name: 'it', amount: 1243 },
//       { id: 21, name: 'network', amount: 567 },
//       { id: 12, name: 'infrastructure', amount: 923 },
//     ],
//     transactionType: 'Purchase Order',
//     amount: 35000,
//   },
//   {
//     id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567832',
//     controlNumber: 'REQ-2025-032',
//     vendor: 'OfficeWorld Stationery',
//     subject: 'Toner Cartridges — Monthly Replenishment',
//     status: RequestStatus.UnderReview,
//     currentStep: 'Department Head Approval',
//     createdOn: '2025-04-17',
//     lastUpdatedOn: '2025-04-18',
//     reviewType: ReviewType.Proposal,
//     funds: [
//       { id: 7, name: 'supplies', amount: 445 },
//       { id: 2, name: 'office', amount: 512 },
//     ],
//     transactionType: 'Purchase Order',
//     amount: 22000,
//   },
//   {
//     id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567833',
//     controlNumber: 'REQ-2025-033',
//     vendor: 'PowerSource Electrical',
//     subject: 'Electrical Wiring Inspection — Branch Office',
//     status: RequestStatus.Rejected,
//     currentStep: 'Finance Approval',
//     createdOn: '2025-04-18',
//     lastUpdatedOn: '2025-04-20',
//     reviewType: ReviewType.Others,
//     funds: [
//       { id: 5, name: 'facilities', amount: 678 },
//       { id: 19, name: 'compliance', amount: 567 },
//       { id: 12, name: 'infrastructure', amount: 923 },
//     ],
//     transactionType: 'Service Contract',
//     amount: 15000,
//   },
//   {
//     id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567834',
//     controlNumber: 'REQ-2025-034',
//     vendor: 'AquaFlow Solutions',
//     subject: 'Water Tank Cleaning — Main Building',
//     status: RequestStatus.Completed,
//     currentStep: 'Released',
//     createdOn: '2025-04-19',
//     lastUpdatedOn: '2025-04-22',
//     reviewType: ReviewType.Proposal,
//     funds: [
//       { id: 5, name: 'facilities', amount: 678 },
//       { id: 16, name: 'maintenance', amount: 834 },
//     ],
//     transactionType: 'Service Contract',
//     amount: 11000,
//   },
//   {
//     id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567835',
//     controlNumber: 'REQ-2025-035',
//     vendor: 'FastPrint Solutions',
//     subject: 'Employee Handbook Reprinting — 2025 Edition',
//     status: RequestStatus.UnderReview,
//     currentStep: 'HR Approval',
//     createdOn: '2025-04-20',
//     lastUpdatedOn: '2025-04-21',
//     reviewType: ReviewType.Proposal,
//     funds: [
//       { id: 17, name: 'hr', amount: 789 },
//       { id: 8, name: 'printing', amount: 187 },
//     ],
//     transactionType: 'Purchase Order',
//     amount: 16500,
//   },
//   {
//     id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567836',
//     controlNumber: 'REQ-2025-036',
//     vendor: 'SafeGuard Security Inc.',
//     subject: 'Access Card System Upgrade — All Floors',
//     status: RequestStatus.Draft,
//     currentStep: 'Requestor Review',
//     createdOn: '2025-04-21',
//     lastUpdatedOn: '2025-04-21',
//     reviewType: ReviewType.Proposal,
//     funds: [
//       { id: 11, name: 'security', amount: 654 },
//       { id: 12, name: 'infrastructure', amount: 923 },
//     ],
//     transactionType: 'Purchase Order',
//     amount: 145000,
//   },
//   {
//     id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567837',
//     controlNumber: 'REQ-2025-037',
//     vendor: 'SolarTech Energy PH',
//     subject: 'Solar Panel Cleaning and Inspection',
//     status: RequestStatus.UnderReview,
//     currentStep: 'VP Operations Approval',
//     createdOn: '2025-04-22',
//     lastUpdatedOn: '2025-04-23',
//     reviewType: ReviewType.Proposal,
//     funds: [
//       { id: 5, name: 'facilities', amount: 678 },
//       { id: 16, name: 'maintenance', amount: 834 },
//       { id: 22, name: 'energy', amount: 178 },
//     ],
//     transactionType: 'Service Contract',
//     amount: 19000,
//   },
//   {
//     id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567838',
//     controlNumber: 'REQ-2025-038',
//     vendor: 'ElitePrint Digital',
//     subject: 'Marketing Collaterals — Q2 Campaign',
//     status: RequestStatus.Returned,
//     currentStep: 'Requestor Review',
//     createdOn: '2025-04-23',
//     lastUpdatedOn: '2025-04-25',
//     reviewType: ReviewType.Others,
//     funds: [
//       { id: 18, name: 'marketing', amount: 312 },
//       { id: 8, name: 'printing', amount: 187 },
//     ],
//     transactionType: 'Purchase Order',
//     amount: 62000,
//   },
//   {
//     id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567839',
//     controlNumber: 'REQ-2025-039',
//     vendor: 'MediCare Supplies PH',
//     subject: 'AED Device Procurement — Lobby',
//     status: RequestStatus.UnderReview,
//     currentStep: 'Finance Approval',
//     createdOn: '2025-04-24',
//     lastUpdatedOn: '2025-04-26',
//     reviewType: ReviewType.Contract,
//     funds: [
//       { id: 13, name: 'health', amount: 312 },
//       { id: 14, name: 'safety', amount: 267 },
//     ],
//     transactionType: 'Purchase Order',
//     amount: 85000,
//   },
//   {
//     id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567840',
//     controlNumber: 'REQ-2025-040',
//     vendor: 'PrimeChem Janitorial',
//     subject: 'Pest Control Service — Quarterly Treatment',
//     status: RequestStatus.Completed,
//     currentStep: 'Released',
//     createdOn: '2025-04-25',
//     lastUpdatedOn: '2025-04-28',
//     reviewType: ReviewType.Proposal,
//     funds: [
//       { id: 5, name: 'facilities', amount: 678 },
//       { id: 16, name: 'maintenance', amount: 834 },
//     ],
//     transactionType: 'Service Contract',
//     amount: 16000,
//   },
//   {
//     id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567841',
//     controlNumber: 'REQ-2025-041',
//     vendor: 'CoolBreeze HVAC Services',
//     subject: 'Chiller Unit Replacement — Server Room',
//     status: RequestStatus.Draft,
//     currentStep: 'Requestor Review',
//     createdOn: '2025-04-26',
//     lastUpdatedOn: '2025-04-26',
//     reviewType: ReviewType.Proposal,
//     funds: [
//       { id: 3, name: 'it', amount: 1243 },
//       { id: 12, name: 'infrastructure', amount: 923 },
//       { id: 5, name: 'facilities', amount: 678 },
//     ],
//     transactionType: 'Purchase Order',
//     amount: 380000,
//   },
//   {
//     id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567842',
//     controlNumber: 'REQ-2025-042',
//     vendor: 'GlobalTravel Solutions',
//     subject: 'Team Building Event — Logistics and Transport',
//     status: RequestStatus.UnderReview,
//     currentStep: 'HR Approval',
//     createdOn: '2025-04-27',
//     lastUpdatedOn: '2025-04-28',
//     reviewType: ReviewType.Others,
//     funds: [
//       { id: 17, name: 'hr', amount: 789 },
//       { id: 9, name: 'events', amount: 356 },
//       { id: 23, name: 'travel', amount: 145 },
//     ],
//     transactionType: 'Service Contract',
//     amount: 195000,
//   },
//   {
//     id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567843',
//     controlNumber: 'REQ-2025-043',
//     vendor: 'BrightMark Advertising',
//     subject: 'Digital Signage Content Update — All Branches',
//     status: RequestStatus.Cancelled,
//     currentStep: 'Cancelled',
//     createdOn: '2025-04-28',
//     lastUpdatedOn: '2025-04-29',
//     reviewType: ReviewType.Proposal,
//     funds: [
//       { id: 18, name: 'marketing', amount: 312 },
//       { id: 3, name: 'it', amount: 1243 },
//     ],
//     transactionType: 'Service Contract',
//     amount: 48000,
//   },
//   {
//     id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567844',
//     controlNumber: 'REQ-2025-044',
//     vendor: 'SecureNet IT Services',
//     subject: 'Endpoint Security Software — 50 Licenses',
//     status: RequestStatus.UnderReview,
//     currentStep: 'IT Manager Approval',
//     createdOn: '2025-04-29',
//     lastUpdatedOn: '2025-04-30',
//     reviewType: ReviewType.Proposal,
//     funds: [
//       { id: 3, name: 'it', amount: 1243 },
//       { id: 11, name: 'security', amount: 654 },
//       { id: 25, name: 'license', amount: 245 },
//     ],
//     transactionType: 'Purchase Order',
//     amount: 135000,
//   },
//   {
//     id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567845',
//     controlNumber: 'REQ-2025-045',
//     vendor: 'Acme Supplies Co.',
//     subject: 'Filing Cabinets — Records Management Room',
//     status: RequestStatus.Completed,
//     currentStep: 'Released',
//     createdOn: '2025-04-30',
//     lastUpdatedOn: '2025-05-03',
//     reviewType: ReviewType.Contract,
//     funds: [
//       { id: 1, name: 'furniture', amount: 234 },
//       { id: 20, name: 'records', amount: 423 },
//       { id: 19, name: 'compliance', amount: 567 },
//     ],
//     transactionType: 'Purchase Order',
//     amount: 42000,
//   },
//   {
//     id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567846',
//     controlNumber: 'REQ-2025-046',
//     vendor: 'ProHealth Medical Supplies',
//     subject: 'Ergonomic Wrist Rests and Mouse Pads — Bulk Order',
//     status: RequestStatus.Draft,
//     currentStep: 'Requestor Review',
//     createdOn: '2025-05-01',
//     lastUpdatedOn: '2025-05-01',
//     reviewType: ReviewType.Proposal,
//     funds: [
//       { id: 13, name: 'health', amount: 312 },
//       { id: 7, name: 'supplies', amount: 445 },
//       { id: 2, name: 'office', amount: 512 },
//     ],
//     transactionType: 'Purchase Order',
//     amount: 9500,
//   },
//   {
//     id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567847',
//     controlNumber: 'REQ-2025-047',
//     vendor: 'SwiftCourier Logistics',
//     subject: 'Same-Day Delivery Service Agreement — Q2',
//     status: RequestStatus.UnderReview,
//     currentStep: 'Operations Approval',
//     createdOn: '2025-05-02',
//     lastUpdatedOn: '2025-05-04',
//     reviewType: ReviewType.Proposal,
//     funds: [
//       { id: 15, name: 'logistics', amount: 445 },
//       { id: 6, name: 'contract', amount: 1000 },
//     ],
//     transactionType: 'Service Contract',
//     amount: 54000,
//   },
//   {
//     id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567848',
//     controlNumber: 'REQ-2025-048',
//     vendor: 'SafeVault Document Storage',
//     subject: 'Secure Shredding Service — Confidential Files',
//     status: RequestStatus.Rejected,
//     currentStep: 'Compliance Approval',
//     createdOn: '2025-05-03',
//     lastUpdatedOn: '2025-05-06',
//     reviewType: ReviewType.Others,
//     funds: [
//       { id: 19, name: 'compliance', amount: 567 },
//       { id: 20, name: 'records', amount: 423 },
//       { id: 11, name: 'security', amount: 654 },
//     ],
//     transactionType: 'Service Contract',
//     amount: 8000,
//   },
//   {
//     id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567849',
//     controlNumber: 'REQ-2025-049',
//     vendor: 'TechZone Philippines',
//     subject: 'Tablet Procurement — Field Operations Team',
//     status: RequestStatus.UnderReview,
//     currentStep: 'Department Head Approval',
//     createdOn: '2025-05-04',
//     lastUpdatedOn: '2025-05-05',
//     reviewType: ReviewType.Contract,
//     funds: [
//       { id: 3, name: 'it', amount: 1243 },
//       { id: 4, name: 'hardware', amount: 891 },
//       { id: 26, name: 'operations', amount: 456 },
//     ],
//     transactionType: 'Purchase Order',
//     amount: 168000,
//   },
//   {
//     id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567850',
//     controlNumber: 'REQ-2025-050',
//     vendor: 'GreenLeaf Catering',
//     subject: 'Employee Appreciation Lunch — May',
//     status: RequestStatus.Completed,
//     currentStep: 'Released',
//     createdOn: '2025-05-05',
//     lastUpdatedOn: '2025-05-08',
//     reviewType: ReviewType.Others,
//     funds: [
//       { id: 10, name: 'catering', amount: 123 },
//       { id: 17, name: 'hr', amount: 789 },
//       { id: 9, name: 'events', amount: 356 },
//     ],
//     transactionType: 'Service Contract',
//     amount: 45000,
//   },
//   {
//     id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567851',
//     controlNumber: 'REQ-2025-051',
//     vendor: 'NetConnect ISP',
//     subject: 'Dedicated Leased Line — Data Center',
//     status: RequestStatus.Draft,
//     currentStep: 'Requestor Review',
//     createdOn: '2025-05-06',
//     lastUpdatedOn: '2025-05-06',
//     reviewType: ReviewType.Contract,
//     funds: [
//       { id: 3, name: 'it', amount: 1243 },
//       { id: 21, name: 'network', amount: 567 },
//       { id: 12, name: 'infrastructure', amount: 923 },
//     ],
//     transactionType: 'Service Contract',
//     amount: 240000,
//   },
//   {
//     id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567852',
//     controlNumber: 'REQ-2025-052',
//     vendor: 'BrightSpark Electrical',
//     subject: 'LED Lighting Retrofit — Warehouse Floor',
//     status: RequestStatus.UnderReview,
//     currentStep: 'Budget Review',
//     createdOn: '2025-05-07',
//     lastUpdatedOn: '2025-05-09',
//     reviewType: ReviewType.Proposal,
//     funds: [
//       { id: 5, name: 'facilities', amount: 678 },
//       { id: 12, name: 'infrastructure', amount: 923 },
//       { id: 22, name: 'energy', amount: 178 },
//     ],
//     transactionType: 'Purchase Order',
//     amount: 72000,
//   },
//   {
//     id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567853',
//     controlNumber: 'REQ-2025-053',
//     vendor: 'UrbanFurniture PH',
//     subject: 'Standing Desks — Executive Floor',
//     status: RequestStatus.Returned,
//     currentStep: 'Requestor Review',
//     createdOn: '2025-05-08',
//     lastUpdatedOn: '2025-05-10',
//     reviewType: ReviewType.Proposal,
//     funds: [
//       { id: 1, name: 'furniture', amount: 234 },
//       { id: 2, name: 'office', amount: 512 },
//     ],
//     transactionType: 'Purchase Order',
//     amount: 128000,
//   },
//   {
//     id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567854',
//     controlNumber: 'REQ-2025-054',
//     vendor: 'ElitePrint Digital',
//     subject: 'Annual Report Printing — Board Copies',
//     status: RequestStatus.UnderReview,
//     currentStep: 'VP Finance Approval',
//     createdOn: '2025-05-09',
//     lastUpdatedOn: '2025-05-11',
//     reviewType: ReviewType.Others,
//     funds: [
//       { id: 8, name: 'printing', amount: 187 },
//       { id: 19, name: 'compliance', amount: 567 },
//       { id: 20, name: 'records', amount: 423 },
//     ],
//     transactionType: 'Purchase Order',
//     amount: 38000,
//   },
//   {
//     id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567855',
//     controlNumber: 'REQ-2025-055',
//     vendor: 'PowerSource Electrical',
//     subject: 'Solar Inverter Replacement — Rooftop Unit',
//     status: RequestStatus.Draft,
//     currentStep: 'Requestor Review',
//     createdOn: '2025-05-10',
//     lastUpdatedOn: '2025-05-10',
//     reviewType: ReviewType.Proposal,
//     funds: [
//       { id: 5, name: 'facilities', amount: 678 },
//       { id: 22, name: 'energy', amount: 178 },
//       { id: 12, name: 'infrastructure', amount: 923 },
//     ],
//     transactionType: 'Purchase Order',
//     amount: 95000,
//   },
// ];

export const mockApprovalActivities = [
  {
    approvalGroupName: "Requestor",
    comments: [
      {
        commenter: "De Marco, Jose",
        comment: "Requesting for external training for the team. The training costs Php10,000.00 for a min of 30pax. Please see provided link for reference.",
        commentedAt: "2024-06-12T09:30:00",
        references: [
          {
            label: 'Training',
            url: 'https://www.google.com',
          },
        ],
      },
      {
        commenter: "Tiongson, Pia",
        comment: "All good for me.",
        commentedAt: "2024-06-12T11:47:00",
        references: [],
      },
    ],
    signatures: [
      {
        name: "De Marco, Jose",
        isSigned: true,
        signedAt: "2024-06-12T12:13:00",
      },
      {
        name: "Tiongson, Pia",
        isSigned: true,
        signedAt: "2024-06-12T17:09:00",
      },
    ],
  },
  {
    approvalGroupName: "Department Head Approval",
    comments: [
      {
        commenter: "Villanueva, Marco",
        comment: "Reviewed the request. Can you confirm whether the training provider is accredited by TESDA or any recognized body? Please attach supporting documentation if available.",
        commentedAt: "2024-06-12T14:20:00",
        references: [],
      },
      {
        commenter: "De Marco, Jose",
        comment: "Hi Sir Marco, the provider is not TESDA-accredited but they are a registered SEC corporation with prior engagements with two of our partner companies. I've added their company profile link under references.",
        commentedAt: "2024-06-12T15:05:00",
        references: [
          {
            label: 'Provider Company Profile',
            url: 'https://www.google.com',
          },
          {
            label: 'Previous Client List',
            url: 'https://www.google.com',
          },
        ],
      },
      {
        commenter: "Villanueva, Marco",
        comment: "Noted. That's acceptable for this type of training. I'll endorse this to Budget Review.",
        commentedAt: "2024-06-13T09:58:00",
        references: [],
      },
    ],
    signatures: [
      {
        name: "Villanueva, Marco",
        isSigned: true,
        signedAt: "2024-06-13T10:45:00",
      },
    ],
  },
  {
    approvalGroupName: "Budget Review",
    comments: [
      {
        commenter: "Reyes, Ana",
        comment: "Checking fund availability. The requested amount of Php300,000.00 (30 pax × Php10,000.00) will be sourced from the Q3 Training and Development fund. Current available balance is Php415,000.00.",
        commentedAt: "2024-06-13T11:10:00",
        references: [
          {
            label: 'Q3 T&D Budget Summary',
            url: 'https://www.google.com',
          },
          {
            label: 'Fund Utilization Policy',
            url: 'https://www.google.com',
          },
        ],
      },
      {
        commenter: "De Marco, Jose",
        comment: "Hi Ma'am Ana, we actually have 32 confirmed participants now. Please let us know if we need to revise the total amount.",
        commentedAt: "2024-06-13T11:48:00",
        references: [],
      },
      {
        commenter: "Reyes, Ana",
        comment: "Yes, please update the request amount to Php320,000.00 to reflect 32 pax. Remaining T&D balance after this will be Php95,000.00. Budget is available — endorsing to Finance.",
        commentedAt: "2024-06-13T13:05:00",
        references: [
          {
            label: 'Budget Request Form',
            url: 'https://www.google.com',
          },
        ],
      },
      {
        commenter: "De Marco, Jose",
        comment: "Understood. Amount has been updated accordingly. Thank you!",
        commentedAt: "2024-06-13T13:31:00",
        references: [],
      },
    ],
    signatures: [
      {
        name: "Reyes, Ana",
        isSigned: true,
        signedAt: "2024-06-13T15:22:00",
      },
      {
        name: "Castillo, Dennis",
        isSigned: true,
        signedAt: "2024-06-14T09:05:00",
      },
    ],
  },
  {
    approvalGroupName: "Finance Approval",
    comments: [
      {
        commenter: "Santos, Lito",
        comment: "Please attach the official quotation from the training provider. We need this for the check voucher preparation.",
        commentedAt: "2024-06-14T14:22:00",
        references: [
          {
            label: 'Accounts Payable Guidelines',
            url: 'https://www.google.com',
          },
          {
            label: 'Check Voucher Template',
            url: 'https://www.google.com',
          },
        ],
      },
      {
        commenter: "De Marco, Jose",
        comment: "Hi Sir Lito, attached is the formal quotation under references. The training is scheduled for July 5–6, 2024.",
        commentedAt: "2024-06-14T15:03:00",
        references: [
          {
            label: 'Official Quotation',
            url: 'https://www.google.com',
          },
          {
            label: 'Training Schedule',
            url: 'https://www.google.com',
          },
        ],
      },
      {
        commenter: "Santos, Lito",
        comment: "Received. One more — are meals and accommodations covered in the Php10,000 rate, or are those billed separately?",
        commentedAt: "2024-06-14T16:10:00",
        references: [],
      },
      {
        commenter: "De Marco, Jose",
        comment: "The rate is inclusive of training materials and AM/PM snacks. Lunch is separate and will be charged to the event budget, not this request.",
        commentedAt: "2024-06-14T16:44:00",
        references: [],
      },
      {
        commenter: "Santos, Lito",
        comment: "Noted and documented. Financials are in order. Forwarding to Finance Head for final sign-off.",
        commentedAt: "2024-06-17T10:55:00",
        references: [],
      },
    ],
    signatures: [
      {
        name: "Santos, Lito",
        isSigned: true,
        signedAt: "2024-06-17T11:30:00",
      },
      {
        name: "Cruz, Maribel",
        isSigned: true,
        signedAt: "2024-06-17T16:55:00",
      },
    ],
  },
  {
    approvalGroupName: "VP Operations Approval",
    comments: [
      {
        commenter: "Alcantara, Roberto",
        comment: "I've reviewed the full endorsement chain. This aligns well with the team's capability roadmap for H2. No objections — approving.",
        commentedAt: "2024-06-18T09:22:00",
        references: [
          {
            label: 'H2 Capability Roadmap',
            url: 'https://www.google.com',
          },
          {
            label: 'HR Training Calendar',
            url: 'https://www.google.com',
          },
        ],
      },
      {
        commenter: "De Marco, Jose",
        comment: "Thank you, Sir Roberto! The team is very much looking forward to this.",
        commentedAt: "2024-06-18T10:14:00",
        references: [],
      },
    ],
    signatures: [
      {
        name: "Alcantara, Roberto",
        isSigned: true,
        signedAt: "2024-06-18T14:15:00",
      },
    ],
  },
  {
    approvalGroupName: "Procurement",
    comments: [
      {
        commenter: "Dizon, Carla",
        comment: "Purchase Order No. PO-2024-1187 has been generated and sent to the supplier. Estimated processing time is 3–5 business days.",
        commentedAt: "2024-06-19T08:35:00",
        references: [
          {
            label: 'PO-2024-1187',
            url: 'https://www.google.com',
          },
          {
            label: 'Supplier Confirmation',
            url: 'https://www.google.com',
          },
        ],
      },
      {
        commenter: "Fuentes, Mark",
        comment: "Check Voucher No. CV-2024-0892 prepared and filed. Payment will be released upon submission of training completion report and official receipt.",
        commentedAt: "2024-06-19T09:02:00",
        references: [
          {
            label: 'CV-2024-0892',
            url: 'https://www.google.com',
          },
          {
            label: 'Payment Release Policy',
            url: 'https://www.google.com',
          },
          {
            label: 'Training Completion Form',
            url: 'https://www.google.com',
          },
        ],
      },
      {
        commenter: "De Marco, Jose",
        comment: "Noted. We'll submit the OR and completion report right after the training on July 6. Thank you everyone!",
        commentedAt: "2024-06-19T09:28:00",
        references: [],
      },
    ],
    signatures: [
      {
        name: "Dizon, Carla",
        isSigned: true,
        signedAt: "2024-06-19T10:00:00",
      },
      {
        name: "Fuentes, Mark",
        isSigned: true,
        signedAt: "2024-06-19T13:48:00",
      },
    ],
  },
  {
    approvalGroupName: "CFO Approval",
    comments: [],
    signatures: [
      {
        name: "Villanueva, Carmen",
        isSigned: false,
        signedAt: null,
      },
    ],
  },
];

export const mockApprovalMatrix = [
  {
    approvalGroupName: "Requestor",
    signatures: ["De Marco, Jose", "Tiongson, Pia"],
  },
  {
    approvalGroupName: "Department Head Approval",
    signatures: ["Villanueva, Marco"],
  },
  {
    approvalGroupName: "Budget Review",
    signatures: ["Reyes, Ana", "Castillo, Dennis"],
  },
  {
    approvalGroupName: "Finance Approval",
    signatures: ["Santos, Lito", "Cruz, Maribel"],
  },
  {
    approvalGroupName: "VP Operations Approval",
    signatures: ["Alcantara, Roberto"],
  },
  {
    approvalGroupName: "Procurement",
    signatures: ["Dizon, Carla", "Fuentes, Mark"],
  },
  {
    approvalGroupName: "CFO Approval",
    signatures: ["Villanueva, Carmen"],
  },
];

export const mockTransactionTypes = [
  { id: 1, name: 'Purchase Order', children: [] },
  { id: 2, name: 'Service Contract', children: [] },
  { id: 3, name: 'Consultancy Agreement', children: [] },
  { id: 4, name: 'Lease Agreement', children: [] },
  { id: 5, name: 'Memorandum of Agreement', children: [] },
  { id: 6, name: 'Request for Quotation', children: [] },
  { id: 7, name: 'Delivery Order', children: [] },
  { id: 8, name: 'Work Order', children: [] },
  { id: 9, name: 'Job Order', children: [] },
  { id: 10, name: 'Supply Agreement', children: [] },
  {
    id: 11, name: 'Equipment',
    children: [
      { id: 12, name: 'Rental', children: [] },
      { id: 13, name: 'Purchase', children: [] },
      { id: 14, name: 'Leasing', children: [] },
    ],
  },
  {
    id: 15, name: 'IT',
    children: [
      { id: 16, name: 'Software License', children: [] },
      { id: 17, name: 'SaaS Subscription', children: [] },
      { id: 18, name: 'Hardware Procurement', children: [] },
      {
        id: 19, name: 'Maintenance',
        children: [
          { id: 20, name: 'Software', children: [] },
          { id: 21, name: 'Hardware', children: [] },
        ],
      },
    ],
  },
  {
    id: 22, name: 'Infrastructure',
    children: [
      { id: 23, name: 'Construction', children: [] },
      { id: 24, name: 'Renovation', children: [] },
      {
        id: 25, name: 'Repair',
        children: [
          { id: 26, name: 'Civil', children: [] },
          { id: 27, name: 'Electrical', children: [] },
          { id: 28, name: 'Mechanical', children: [] },
        ],
      },
    ],
  },
];

export const mockApprovers = [
  { id: 1, name: 'Santos, Maria' },
  { id: 2, name: 'Reyes, Juan' },
  { id: 3, name: 'Cruz, Ana' },
  { id: 4, name: 'Garcia, Luis' },
  { id: 5, name: 'Torres, Carmen' },
  { id: 6, name: 'Boyle, Charles' },
  { id: 7, name: 'Holt, Raymond' },
  { id: 8, name: 'Cooper, Sheldon' },
  { id: 9, name: 'Dalisay, Cardo' },
];

export const mockEditDraftRequest: EditDraftRequest = {
  id: 'f3a1c2d4-e5b6-7890-abcd-ef1234567890',
  status: RequestStatus.Draft,
  subject: 'Office Chairs Procurement — Q3',
  vendor: 'UrbanFurniture PH',
  reviewType: ReviewType.Contract,
  funds: [
    { id: 1, name: 'furniture', amount: 45000 },
    { id: 2, name: 'office', amount: 12000 },
  ],
  transactionType: { id: 1, name: 'Purchase Order' },
  amountBracket: AmountOption.UpTo1M,
  preapproverManager: { id: 4, displayName: 'Garcia, Luis' },
  comment: {
    commenter: 'De Marco, Jose',
    commentedAt: '2026-04-24T10:15:00',
    comment: 'Requesting procurement of ergonomic office chairs for the operations floor. See attached reference for the selected model.',
    references: [
      { label: 'Product Catalog', url: 'https://www.google.com' },
    ],
  } as ApprovalComment
};

export const mockRequestsV2 = [
  {
    id: 'a3f7c2d1-84e6-4b2a-9c5f-1d8e3b7a0f4c',
    controlNumber: '25-0001',
    subject: 'Procurement of Office Supplies',
    vendor: 'ABC Supplies Co.',
    reviewType: ReviewType.Contract,
    funds: [
      { id: 1, name: 'General Fund', amount: 150000 },
    ],
    transactionType: { id: 1, name: 'Purchase Order' },
    amountBracket: AmountOption.UpTo1M,
    status: RequestStatus.Completed,
    currentStepName: 'COO',
    hasApprovals: true,
    createdAt: '2025-01-05T08:00:00Z',
    updatedAt: '2025-01-06T09:30:00Z',
    submittedAt: '2025-01-06T10:00:00Z',
    completedAt: '2025-01-20T15:00:00Z',
  },
  {
    id: 'b1e4d8f2-3a7c-4f91-b6d2-5e9c0a2f8b3d',
    controlNumber: '',
    subject: 'IT Infrastructure Upgrade',
    vendor: 'TechVision Solutions',
    reviewType: ReviewType.Proposal,
    funds: [
      { id: 3, name: 'Trust Fund', amount: 600000 },
      { id: 5, name: 'Development Fund', amount: 500000 },
    ],
    transactionType: { id: 18, name: 'Hardware Procurement' },
    amountBracket: AmountOption.Above1M,
    status: RequestStatus.Draft,
    createdAt: '2025-01-10T09:00:00Z',
    updatedAt: '2025-01-12T11:00:00Z',
  },
  {
    id: 'c9d2a5e3-6b1f-4e8d-a7c4-2f0b9e6d3a1c',
    controlNumber: '25-0003',
    subject: 'Legal Consultancy for Contract Review',
    vendor: 'Reyes & Partners Law Offices',
    reviewType: ReviewType.Contract,
    funds: [
      { id: 1, name: 'General Fund', amount: 250000 },
    ],
    transactionType: { id: 3, name: 'Consultancy Agreement' },
    amountBracket: AmountOption.UpTo1M,
    status: RequestStatus.Rejected,
    currentStepName: 'Finance Team',
    hasApprovals: false,
    createdAt: '2025-01-15T07:30:00Z',
    updatedAt: '2025-01-16T08:00:00Z',
    submittedAt: '2025-01-16T09:00:00Z',
    rejectedAt: '2025-01-25T14:00:00Z',
  },
  {
    id: 'd4f8b1a6-2c5e-4d9f-b3a7-8e1c0f4d7b2e',
    controlNumber: '25-0004',
    subject: 'School Building Renovation',
    vendor: 'BuildRight Construction Inc.',
    reviewType: ReviewType.Proposal,
    funds: [
      { id: 2, name: 'Special Education Fund', amount: 800000 },
      { id: 5, name: 'Development Fund', amount: 700000 },
    ],
    transactionType: { id: 24, name: 'Renovation' },
    amountBracket: AmountOption.Above1M,
    status: RequestStatus.Completed,
    currentStepName: 'COO',
    hasApprovals: true,
    createdAt: '2025-02-01T08:00:00Z',
    updatedAt: '2025-02-03T10:00:00Z',
    submittedAt: '2025-02-03T11:30:00Z',
    completedAt: '2025-03-01T16:00:00Z',
  },
  {
    id: 'e7a3c6f9-1d4b-4a2e-8f5c-3b0d9e7a4f1b',
    controlNumber: '',
    subject: 'SaaS Subscription for HR System',
    vendor: 'CloudHR Philippines',
    reviewType: ReviewType.Others,
    reviewTypeOther: 'Software Evaluation',
    funds: [
      { id: 1, name: 'General Fund', amount: 180000 },
    ],
    transactionType: { id: 17, name: 'SaaS Subscription' },
    amountBracket: AmountOption.UpTo1M,
    status: RequestStatus.Draft,
    createdAt: '2025-02-10T09:00:00Z',
    updatedAt: '2025-02-11T10:30:00Z',
  },
  {
    id: 'f2b5d9e1-7a3c-4f6b-a1d8-4c0e2b5f9d3a',
    controlNumber: '25-0006',
    subject: 'Calamity Response Equipment Rental',
    vendor: 'Rapid Response Equipment Corp.',
    reviewType: ReviewType.Contract,
    funds: [
      { id: 4, name: 'Calamity Fund', amount: 450000 },
    ],
    transactionType: { id: 12, name: 'Rental' },
    amountBracket: AmountOption.UpTo1M,
    status: RequestStatus.Completed,
    currentStepName: 'COO',
    hasApprovals: true,
    createdAt: '2025-02-14T06:00:00Z',
    updatedAt: '2025-02-14T08:00:00Z',
    submittedAt: '2025-02-14T08:30:00Z',
    completedAt: '2025-02-28T17:00:00Z',
  },
  {
    id: '1a4c7f3e-5b2d-4e8a-9f6c-0d3b1e7a5c2f',
    controlNumber: '25-0007',
    subject: 'Road Repair along Barangay Access Road',
    vendor: 'Metro Civil Works Co.',
    reviewType: ReviewType.Proposal,
    funds: [
      { id: 5, name: 'Development Fund', amount: 950000 },
    ],
    transactionType: { id: 26, name: 'Civil' },
    amountBracket: AmountOption.UpTo1M,
    status: RequestStatus.UnderReview,
    currentStepName: 'Purchasing',
    hasApprovals: false,
    createdAt: '2025-03-01T07:00:00Z',
    updatedAt: '2025-03-02T09:00:00Z',
    submittedAt: '2025-03-02T10:00:00Z',
  },
  {
    id: '2b5d8e4f-6c1a-4f9b-a3e7-1d4c0f8b6a2e',
    controlNumber: '',
    subject: 'Software License for Accounting System',
    vendor: 'FinSoft Technologies',
    reviewType: ReviewType.Contract,
    funds: [
      { id: 1, name: 'General Fund', amount: 320000 },
      { id: 3, name: 'Trust Fund', amount: 80000 },
    ],
    transactionType: { id: 16, name: 'Software License' },
    amountBracket: AmountOption.UpTo1M,
    status: RequestStatus.Draft,
    createdAt: '2025-03-05T08:30:00Z',
    updatedAt: '2025-03-06T09:00:00Z',
  },
  {
    id: '3c6e9f5a-7d2b-4a1c-b4f8-2e5d1b9c7f3a',
    controlNumber: '25-0009',
    subject: 'Memorandum of Agreement with State University',
    vendor: 'Mindanao State University',
    reviewType: ReviewType.Others,
    reviewTypeOther: 'Partnership Agreement',
    funds: [
      { id: 2, name: 'Special Education Fund', amount: 500000 },
    ],
    transactionType: { id: 5, name: 'Memorandum of Agreement' },
    amountBracket: AmountOption.UpTo1M,
    status: RequestStatus.Returned,
    currentStepName: 'Requestor',
    hasApprovals: true,
    createdAt: '2025-03-10T10:00:00Z',
    updatedAt: '2025-03-11T11:00:00Z',
    submittedAt: '2025-03-11T13:00:00Z',
  },
  {
    id: '4d7f0a6b-8e3c-4b2d-c5a9-3f6e2c0d8a4b',
    controlNumber: '25-0010',
    subject: 'Electrical System Repair for Municipal Hall',
    vendor: 'PowerFix Electrical Services',
    reviewType: ReviewType.Contract,
    funds: [
      { id: 1, name: 'General Fund', amount: 275000 },
      { id: 5, name: 'Development Fund', amount: 125000 },
    ],
    transactionType: { id: 27, name: 'Electrical' },
    amountBracket: AmountOption.UpTo1M,
    status: RequestStatus.Rejected,
    currentStepName: 'Due Diligence',
    hasApprovals: false,
    createdAt: '2025-03-15T07:00:00Z',
    updatedAt: '2025-03-16T08:30:00Z',
    submittedAt: '2025-03-16T09:00:00Z',
    rejectedAt: '2025-03-22T10:00:00Z',
  },
  {
    id: '5e8a1b7c-9f4d-4c3e-d6b0-4a7f3d1e9b5c',
    controlNumber: '25-0011',
    subject: 'Supply of Medical Equipment for Rural Health Units',
    vendor: 'MediSupply Philippines Inc.',
    reviewType: ReviewType.Proposal,
    funds: [
      { id: 1, name: 'General Fund', amount: 750000 },
      { id: 2, name: 'Special Education Fund', amount: 300000 },
      { id: 3, name: 'Trust Fund', amount: 200000 },
      { id: 4, name: 'Calamity Fund', amount: 500000 },
      { id: 5, name: 'Development Fund', amount: 250000 },
      { id: 1, name: 'General Fund', amount: 100000 },
      { id: 2, name: 'Special Education Fund', amount: 150000 },
      { id: 3, name: 'Trust Fund', amount: 80000 },
      { id: 4, name: 'Calamity Fund', amount: 120000 },
      { id: 5, name: 'Development Fund', amount: 50000 },
    ],
    transactionType: { id: 10, name: 'Supply Agreement' },
    amountBracket: AmountOption.Above1M,
    status: RequestStatus.Completed,
    currentStepName: 'COO',
    hasApprovals: false,
    createdAt: '2025-03-20T09:00:00Z',
    updatedAt: '2025-03-22T11:00:00Z',
    submittedAt: '2025-03-22T13:30:00Z',
    completedAt: '2025-04-10T16:00:00Z',
  },
];
