// TODO: Remove this file once endpoint or mock server is established
import { RequestStatus, ReviewType, ApprovalRequest, Fund } from "./shared/types/request-type";

export const mockRequests: ApprovalRequest[] = [
  {
    id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567801',
    controlNo: 'REQ-2025-001',
    vendor: 'Acme Supplies Co.',
    subject: 'Office Furniture Procurement',
    status: RequestStatus.UnderReview,
    currentStep: 'Department Head Approval',
    createdOn: '2025-03-01',
    lastUpdatedOn: '2025-03-05',
    reviewTypes: [ReviewType.Contract],
    funds: [
      { id: 1, amount: 234 },
      { id: 2, amount: 512 },
    ],
    transactionType: 'Purchase Order',
    amount: 150000,
  },
  {
    id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567802',
    controlNo: 'REQ-2025-002',
    vendor: 'TechZone Philippines',
    subject: 'Laptop Replacement — IT Team',
    status: RequestStatus.UnderReview,
    currentStep: 'Budget Review',
    createdOn: '2025-03-08',
    lastUpdatedOn: '2025-03-09',
    reviewTypes: [ReviewType.Proposal],
    funds: [
      { id: 3, amount: 1243 },
      { id: 4, amount: 891 },
    ],
    transactionType: 'Purchase Order',
    amount: 320000,
  },
  {
    id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567803',
    controlNo: 'REQ-2025-003',
    vendor: 'CleanPro Services',
    subject: 'Monthly Janitorial Contract Renewal',
    status: RequestStatus.UnderReview,
    currentStep: 'Finance Approval',
    createdOn: '2025-03-10',
    lastUpdatedOn: '2025-03-12',
    reviewTypes: [ReviewType.Proposal],
    funds: [
      { id: 5, amount: 678 },
      { id: 6, amount: 1000 },
    ],
    transactionType: 'Service Contract',
    amount: 45000,
  },
  {
    id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567804',
    controlNo: 'REQ-2025-004',
    vendor: 'FastPrint Solutions',
    subject: 'Printing Supplies — Q2 Stock',
    status: RequestStatus.Draft,
    currentStep: 'Department Head Approval',
    createdOn: '2025-03-15',
    lastUpdatedOn: '2025-03-15',
    reviewTypes: [ReviewType.Proposal],
    funds: [
      { id: 7, amount: 445 },
      { id: 8, amount: 187 },
    ],
    transactionType: 'Purchase Order',
    amount: 18500,
  },
  {
    id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567805',
    controlNo: 'REQ-2025-005',
    vendor: 'GreenLeaf Catering',
    subject: 'Annual Company Outing Catering',
    status: RequestStatus.UnderReview,
    currentStep: 'VP Operations Approval',
    createdOn: '2025-03-18',
    lastUpdatedOn: '2025-03-20',
    reviewTypes: [ReviewType.Contract, ReviewType.Others],
    funds: [
      { id: 20, amount: 356 },
      { id: 26, amount: 123 },
    ],
    transactionType: 'Service Contract',
    amount: 280000,
  },
  {
    id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567806',
    controlNo: 'REQ-2025-006',
    vendor: 'SafeGuard Security Inc.',
    subject: 'CCTV System Upgrade — Main Office',
    status: RequestStatus.Draft,
    currentStep: 'Requestor Review',
    createdOn: '2025-03-20',
    lastUpdatedOn: '2025-03-20',
    reviewTypes: [ReviewType.Proposal],
    funds: [
      { id: 9, amount: 654 },
      { id: 3, amount: 1243 },
      { id: 10, amount: 923 },
    ],
    transactionType: 'Purchase Order',
    amount: 95000,
  },
  {
    id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567807',
    controlNo: 'REQ-2025-007',
    vendor: 'MediCare Supplies PH',
    subject: 'First Aid Kit Restocking — All Floors',
    status: RequestStatus.Completed,
    currentStep: 'Released',
    createdOn: '2025-03-21',
    lastUpdatedOn: '2025-03-28',
    reviewTypes: [ReviewType.Proposal],
    funds: [
      { id: 12, amount: 312 },
      { id: 13, amount: 267 },
      { id: 7, amount: 445 },
    ],
    transactionType: 'Purchase Order',
    amount: 12000,
  },
  {
    id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567808',
    controlNo: 'REQ-2025-008',
    vendor: 'SwiftCourier Logistics',
    subject: 'Courier Service Contract — Q2',
    status: RequestStatus.Rejected,
    currentStep: 'Budget Review',
    createdOn: '2025-03-22',
    lastUpdatedOn: '2025-03-25',
    reviewTypes: [ReviewType.Proposal],
    funds: [
      { id: 14, amount: 445 },
      { id: 6, amount: 1000 },
    ],
    transactionType: 'Service Contract',
    amount: 36000,
  },
  {
    id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567809',
    controlNo: 'REQ-2025-009',
    vendor: 'PowerSource Electrical',
    subject: 'UPS Unit Replacement — Server Room',
    status: RequestStatus.UnderReview,
    currentStep: 'Finance Approval',
    createdOn: '2025-03-23',
    lastUpdatedOn: '2025-03-26',
    reviewTypes: [ReviewType.Proposal],
    funds: [
      { id: 3, amount: 1243 },
      { id: 10, amount: 923 },
      { id: 4, amount: 891 },
    ],
    transactionType: 'Purchase Order',
    amount: 75000,
  },
  {
    id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567810',
    controlNo: 'REQ-2025-010',
    vendor: 'UrbanFurniture PH',
    subject: 'Ergonomic Chairs — HR Department',
    status: RequestStatus.Returned,
    currentStep: 'Requestor Review',
    createdOn: '2025-03-24',
    lastUpdatedOn: '2025-03-27',
    reviewTypes: [ReviewType.Contract],
    funds: [
      { id: 1, amount: 234 },
      { id: 16, amount: 789 },
    ],
    transactionType: 'Purchase Order',
    amount: 64000,
  },
  {
    id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567811',
    controlNo: 'REQ-2025-011',
    vendor: 'AquaFlow Solutions',
    subject: 'Water Dispenser Maintenance Contract',
    status: RequestStatus.Completed,
    currentStep: 'Released',
    createdOn: '2025-03-25',
    lastUpdatedOn: '2025-04-01',
    reviewTypes: [ReviewType.Proposal],
    funds: [
      { id: 5, amount: 678 },
      { id: 11, amount: 834 },
    ],
    transactionType: 'Service Contract',
    amount: 24000,
  },
  {
    id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567812',
    controlNo: 'REQ-2025-012',
    vendor: 'BrightMark Advertising',
    subject: 'Tarpaulin Printing — Company Anniversary',
    status: RequestStatus.Cancelled,
    currentStep: 'Cancelled',
    createdOn: '2025-03-26',
    lastUpdatedOn: '2025-03-27',
    reviewTypes: [ReviewType.Others],
    funds: [
      { id: 19, amount: 312 },
      { id: 20, amount: 356 },
    ],
    transactionType: 'Purchase Order',
    amount: 8500,
  },
  {
    id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567813',
    controlNo: 'REQ-2025-013',
    vendor: 'NetConnect ISP',
    subject: 'Fiber Internet Upgrade — Branch Office',
    status: RequestStatus.UnderReview,
    currentStep: 'VP Operations Approval',
    createdOn: '2025-03-27',
    lastUpdatedOn: '2025-03-30',
    reviewTypes: [ReviewType.Proposal],
    funds: [
      { id: 3, amount: 1243 },
      { id: 10, amount: 923 },
      { id: 22, amount: 567 },
    ],
    transactionType: 'Service Contract',
    amount: 120000,
  },
  {
    id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567814',
    controlNo: 'REQ-2025-014',
    vendor: 'ElitePrint Digital',
    subject: 'ID Card Printing — New Hires Batch 1',
    status: RequestStatus.Completed,
    currentStep: 'Released',
    createdOn: '2025-03-28',
    lastUpdatedOn: '2025-04-03',
    reviewTypes: [ReviewType.Contract],
    funds: [
      { id: 16, amount: 789 },
      { id: 6, amount: 234 },
    ],
    transactionType: 'Purchase Order',
    amount: 5500,
  },
  {
    id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567815',
    controlNo: 'REQ-2025-015',
    vendor: 'TechZone Philippines',
    subject: 'Network Switch Replacement — Floor 3',
    status: RequestStatus.Draft,
    currentStep: 'Requestor Review',
    createdOn: '2025-03-29',
    lastUpdatedOn: '2025-03-29',
    reviewTypes: [ReviewType.Proposal],
    funds: [
      { id: 3, amount: 1243 },
      { id: 22, amount: 567 },
      { id: 4, amount: 891 },
    ],
    transactionType: 'Purchase Order',
    amount: 48000,
  },
  {
    id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567816',
    controlNo: 'REQ-2025-016',
    vendor: 'PrimeChem Janitorial',
    subject: 'Cleaning Supplies — Monthly Replenishment',
    status: RequestStatus.UnderReview,
    currentStep: 'Department Head Approval',
    createdOn: '2025-03-30',
    lastUpdatedOn: '2025-04-01',
    reviewTypes: [ReviewType.Proposal],
    funds: [
      { id: 5, amount: 678 },
      { id: 7, amount: 445 },
    ],
    transactionType: 'Purchase Order',
    amount: 9800,
  },
  {
    id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567817',
    controlNo: 'REQ-2025-017',
    vendor: 'SolarTech Energy PH',
    subject: 'Solar Panel Installation — Rooftop',
    status: RequestStatus.Returned,
    currentStep: 'Requestor Review',
    createdOn: '2025-04-01',
    lastUpdatedOn: '2025-04-04',
    reviewTypes: [ReviewType.Contract],
    funds: [
      { id: 5, amount: 678 },
      { id: 10, amount: 923 },
      { id: 25, amount: 178 },
    ],
    transactionType: 'Purchase Order',
    amount: 850000,
  },
  {
    id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567818',
    controlNo: 'REQ-2025-018',
    vendor: 'OfficeWorld Stationery',
    subject: 'Stationery and Bond Paper — Q2 Stock',
    status: RequestStatus.Rejected,
    currentStep: 'Finance Approval',
    createdOn: '2025-04-02',
    lastUpdatedOn: '2025-04-05',
    reviewTypes: [ReviewType.Proposal],
    funds: [
      { id: 7, amount: 445 },
      { id: 2, amount: 512 },
    ],
    transactionType: 'Purchase Order',
    amount: 14200,
  },
  {
    id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567819',
    controlNo: 'REQ-2025-019',
    vendor: 'CoolBreeze HVAC Services',
    subject: 'Aircon Preventive Maintenance — All Units',
    status: RequestStatus.UnderReview,
    currentStep: 'Budget Review',
    createdOn: '2025-04-03',
    lastUpdatedOn: '2025-04-06',
    reviewTypes: [ReviewType.Proposal],
    funds: [
      { id: 5, amount: 678 },
      { id: 11, amount: 834 },
    ],
    transactionType: 'Service Contract',
    amount: 58000,
  },
  {
    id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567820',
    controlNo: 'REQ-2025-020',
    vendor: 'SafeVault Document Storage',
    subject: 'Offsite Document Archiving — FY2024 Records',
    status: RequestStatus.Draft,
    currentStep: 'Requestor Review',
    createdOn: '2025-04-05',
    lastUpdatedOn: '2025-04-05',
    reviewTypes: [ReviewType.Others],
    funds: [
      { id: 17, amount: 567 },
      { id: 18, amount: 423 },
    ],
    transactionType: 'Service Contract',
    amount: 32000,
  },
  {
    id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567821',
    controlNo: 'REQ-2025-021',
    vendor: 'ProHealth Medical Supplies',
    subject: 'Annual Medical Exam — All Employees',
    status: RequestStatus.UnderReview,
    currentStep: 'HR Approval',
    createdOn: '2025-04-06',
    lastUpdatedOn: '2025-04-07',
    reviewTypes: [ReviewType.Proposal],
    funds: [
      { id: 12, amount: 312 },
      { id: 16, amount: 789 },
      { id: 17, amount: 567 },
    ],
    transactionType: 'Service Contract',
    amount: 175000,
  },
  {
    id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567822',
    controlNo: 'REQ-2025-022',
    vendor: 'GlobalTravel Solutions',
    subject: 'Business Travel Arrangements — Q2 Conferences',
    status: RequestStatus.Rejected,
    currentStep: 'VP Finance Approval',
    createdOn: '2025-04-07',
    lastUpdatedOn: '2025-04-09',
    reviewTypes: [ReviewType.Others],
    funds: [
      { id: 21, amount: 145 },
      { id: 20, amount: 356 },
    ],
    transactionType: 'Service Contract',
    amount: 220000,
  },
  {
    id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567823',
    controlNo: 'REQ-2025-023',
    vendor: 'SwiftCourier Logistics',
    subject: 'Express Delivery Service — Legal Documents',
    status: RequestStatus.Completed,
    currentStep: 'Released',
    createdOn: '2025-04-08',
    lastUpdatedOn: '2025-04-10',
    reviewTypes: [ReviewType.Others],
    funds: [
      { id: 14, amount: 445 },
      { id: 15, amount: 89 },
    ],
    transactionType: 'Service Contract',
    amount: 4500,
  },
  {
    id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567824',
    controlNo: 'REQ-2025-024',
    vendor: 'TechZone Philippines',
    subject: 'Monitor Replacement — Finance Department',
    status: RequestStatus.UnderReview,
    currentStep: 'Budget Review',
    createdOn: '2025-04-09',
    lastUpdatedOn: '2025-04-11',
    reviewTypes: [ReviewType.Proposal],
    funds: [
      { id: 3, amount: 1243 },
      { id: 4, amount: 891 },
    ],
    transactionType: 'Purchase Order',
    amount: 86000,
  },
  {
    id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567825',
    controlNo: 'REQ-2025-025',
    vendor: 'BrightSpark Electrical',
    subject: 'Emergency Generator Maintenance',
    status: RequestStatus.Draft,
    currentStep: 'Requestor Review',
    createdOn: '2025-04-10',
    lastUpdatedOn: '2025-04-10',
    reviewTypes: [ReviewType.Proposal],
    funds: [
      { id: 5, amount: 678 },
      { id: 11, amount: 834 },
      { id: 10, amount: 923 },
    ],
    transactionType: 'Service Contract',
    amount: 42000,
  },
  {
    id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567826',
    controlNo: 'REQ-2025-026',
    vendor: 'Acme Supplies Co.',
    subject: 'Whiteboard and Markers — Training Room',
    status: RequestStatus.Cancelled,
    currentStep: 'Cancelled',
    createdOn: '2025-04-11',
    lastUpdatedOn: '2025-04-12',
    reviewTypes: [ReviewType.Contract],
    funds: [
      { id: 7, amount: 445 },
      { id: 23, amount: 167 },
    ],
    transactionType: 'Purchase Order',
    amount: 7200,
  },
  {
    id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567827',
    controlNo: 'REQ-2025-027',
    vendor: 'SecureNet IT Services',
    subject: 'Firewall License Renewal — HQ',
    status: RequestStatus.UnderReview,
    currentStep: 'IT Manager Approval',
    createdOn: '2025-04-12',
    lastUpdatedOn: '2025-04-14',
    reviewTypes: [ReviewType.Proposal],
    funds: [
      { id: 3, amount: 1243 },
      { id: 9, amount: 654 },
      { id: 24, amount: 245 },
    ],
    transactionType: 'Service Contract',
    amount: 98000,
  },
  {
    id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567828',
    controlNo: 'REQ-2025-028',
    vendor: 'UrbanFurniture PH',
    subject: 'Reception Area Sofa Set Replacement',
    status: RequestStatus.Returned,
    currentStep: 'Requestor Review',
    createdOn: '2025-04-13',
    lastUpdatedOn: '2025-04-15',
    reviewTypes: [ReviewType.Proposal],
    funds: [
      { id: 1, amount: 234 },
      { id: 5, amount: 678 },
    ],
    transactionType: 'Purchase Order',
    amount: 55000,
  },
  {
    id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567829',
    controlNo: 'REQ-2025-029',
    vendor: 'GreenLeaf Catering',
    subject: 'Board Meeting Catering — April Sessions',
    status: RequestStatus.Completed,
    currentStep: 'Released',
    createdOn: '2025-04-14',
    lastUpdatedOn: '2025-04-16',
    reviewTypes: [ReviewType.Others],
    funds: [
      { id: 26, amount: 123 },
      { id: 20, amount: 356 },
    ],
    transactionType: 'Service Contract',
    amount: 18000,
  },
  {
    id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567830',
    controlNo: 'REQ-2025-030',
    vendor: 'CleanPro Services',
    subject: 'Deep Cleaning Service — Warehouse',
    status: RequestStatus.UnderReview,
    currentStep: 'Operations Approval',
    createdOn: '2025-04-15',
    lastUpdatedOn: '2025-04-17',
    reviewTypes: [ReviewType.Proposal],
    funds: [
      { id: 5, amount: 678 },
      { id: 11, amount: 834 },
    ],
    transactionType: 'Service Contract',
    amount: 28000,
  },
  {
    id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567831',
    controlNo: 'REQ-2025-031',
    vendor: 'NetConnect ISP',
    subject: 'Wi-Fi Access Point Installation — Floor 4',
    status: RequestStatus.Draft,
    currentStep: 'Requestor Review',
    createdOn: '2025-04-16',
    lastUpdatedOn: '2025-04-16',
    reviewTypes: [ReviewType.Contract],
    funds: [
      { id: 3, amount: 1243 },
      { id: 22, amount: 567 },
      { id: 10, amount: 923 },
    ],
    transactionType: 'Purchase Order',
    amount: 35000,
  },
  {
    id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567832',
    controlNo: 'REQ-2025-032',
    vendor: 'OfficeWorld Stationery',
    subject: 'Toner Cartridges — Monthly Replenishment',
    status: RequestStatus.UnderReview,
    currentStep: 'Department Head Approval',
    createdOn: '2025-04-17',
    lastUpdatedOn: '2025-04-18',
    reviewTypes: [ReviewType.Proposal],
    funds: [
      { id: 7, amount: 445 },
      { id: 2, amount: 512 },
    ],
    transactionType: 'Purchase Order',
    amount: 22000,
  },
  {
    id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567833',
    controlNo: 'REQ-2025-033',
    vendor: 'PowerSource Electrical',
    subject: 'Electrical Wiring Inspection — Branch Office',
    status: RequestStatus.Rejected,
    currentStep: 'Finance Approval',
    createdOn: '2025-04-18',
    lastUpdatedOn: '2025-04-20',
    reviewTypes: [ReviewType.Others],
    funds: [
      { id: 5, amount: 678 },
      { id: 17, amount: 567 },
      { id: 10, amount: 923 },
    ],
    transactionType: 'Service Contract',
    amount: 15000,
  },
  {
    id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567834',
    controlNo: 'REQ-2025-034',
    vendor: 'AquaFlow Solutions',
    subject: 'Water Tank Cleaning — Main Building',
    status: RequestStatus.Completed,
    currentStep: 'Released',
    createdOn: '2025-04-19',
    lastUpdatedOn: '2025-04-22',
    reviewTypes: [ReviewType.Proposal],
    funds: [
      { id: 5, amount: 678 },
      { id: 11, amount: 834 },
    ],
    transactionType: 'Service Contract',
    amount: 11000,
  },
  {
    id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567835',
    controlNo: 'REQ-2025-035',
    vendor: 'FastPrint Solutions',
    subject: 'Employee Handbook Reprinting — 2025 Edition',
    status: RequestStatus.UnderReview,
    currentStep: 'HR Approval',
    createdOn: '2025-04-20',
    lastUpdatedOn: '2025-04-21',
    reviewTypes: [ReviewType.Proposal],
    funds: [
      { id: 16, amount: 789 },
      { id: 8, amount: 187 },
    ],
    transactionType: 'Purchase Order',
    amount: 16500,
  },
  {
    id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567836',
    controlNo: 'REQ-2025-036',
    vendor: 'SafeGuard Security Inc.',
    subject: 'Access Card System Upgrade — All Floors',
    status: RequestStatus.Draft,
    currentStep: 'Requestor Review',
    createdOn: '2025-04-21',
    lastUpdatedOn: '2025-04-21',
    reviewTypes: [ReviewType.Proposal],
    funds: [
      { id: 9, amount: 654 },
      { id: 10, amount: 923 },
    ],
    transactionType: 'Purchase Order',
    amount: 145000,
  },
  {
    id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567837',
    controlNo: 'REQ-2025-037',
    vendor: 'SolarTech Energy PH',
    subject: 'Solar Panel Cleaning and Inspection',
    status: RequestStatus.UnderReview,
    currentStep: 'VP Operations Approval',
    createdOn: '2025-04-22',
    lastUpdatedOn: '2025-04-23',
    reviewTypes: [ReviewType.Proposal],
    funds: [
      { id: 5, amount: 678 },
      { id: 11, amount: 834 },
      { id: 25, amount: 178 },
    ],
    transactionType: 'Service Contract',
    amount: 19000,
  },
  {
    id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567838',
    controlNo: 'REQ-2025-038',
    vendor: 'ElitePrint Digital',
    subject: 'Marketing Collaterals — Q2 Campaign',
    status: RequestStatus.Returned,
    currentStep: 'Requestor Review',
    createdOn: '2025-04-23',
    lastUpdatedOn: '2025-04-25',
    reviewTypes: [ReviewType.Others],
    funds: [
      { id: 19, amount: 312 },
      { id: 8, amount: 187 },
    ],
    transactionType: 'Purchase Order',
    amount: 62000,
  },
  {
    id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567839',
    controlNo: 'REQ-2025-039',
    vendor: 'MediCare Supplies PH',
    subject: 'AED Device Procurement — Lobby',
    status: RequestStatus.UnderReview,
    currentStep: 'Finance Approval',
    createdOn: '2025-04-24',
    lastUpdatedOn: '2025-04-26',
    reviewTypes: [ReviewType.Contract],
    funds: [
      { id: 12, amount: 312 },
      { id: 13, amount: 267 },
    ],
    transactionType: 'Purchase Order',
    amount: 85000,
  },
  {
    id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567840',
    controlNo: 'REQ-2025-040',
    vendor: 'PrimeChem Janitorial',
    subject: 'Pest Control Service — Quarterly Treatment',
    status: RequestStatus.Completed,
    currentStep: 'Released',
    createdOn: '2025-04-25',
    lastUpdatedOn: '2025-04-28',
    reviewTypes: [ReviewType.Proposal],
    funds: [
      { id: 5, amount: 678 },
      { id: 11, amount: 834 },
    ],
    transactionType: 'Service Contract',
    amount: 16000,
  },
  {
    id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567841',
    controlNo: 'REQ-2025-041',
    vendor: 'CoolBreeze HVAC Services',
    subject: 'Chiller Unit Replacement — Server Room',
    status: RequestStatus.Draft,
    currentStep: 'Requestor Review',
    createdOn: '2025-04-26',
    lastUpdatedOn: '2025-04-26',
    reviewTypes: [ReviewType.Proposal],
    funds: [
      { id: 3, amount: 1243 },
      { id: 10, amount: 923 },
      { id: 5, amount: 678 },
    ],
    transactionType: 'Purchase Order',
    amount: 380000,
  },
  {
    id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567842',
    controlNo: 'REQ-2025-042',
    vendor: 'GlobalTravel Solutions',
    subject: 'Team Building Event — Logistics and Transport',
    status: RequestStatus.UnderReview,
    currentStep: 'HR Approval',
    createdOn: '2025-04-27',
    lastUpdatedOn: '2025-04-28',
    reviewTypes: [ReviewType.Others],
    funds: [
      { id: 16, amount: 789 },
      { id: 20, amount: 356 },
      { id: 21, amount: 145 },
    ],
    transactionType: 'Service Contract',
    amount: 195000,
  },
  {
    id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567843',
    controlNo: 'REQ-2025-043',
    vendor: 'BrightMark Advertising',
    subject: 'Digital Signage Content Update — All Branches',
    status: RequestStatus.Cancelled,
    currentStep: 'Cancelled',
    createdOn: '2025-04-28',
    lastUpdatedOn: '2025-04-29',
    reviewTypes: [ReviewType.Proposal],
    funds: [
      { id: 19, amount: 312 },
      { id: 3, amount: 1243 },
    ],
    transactionType: 'Service Contract',
    amount: 48000,
  },
  {
    id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567844',
    controlNo: 'REQ-2025-044',
    vendor: 'SecureNet IT Services',
    subject: 'Endpoint Security Software — 50 Licenses',
    status: RequestStatus.UnderReview,
    currentStep: 'IT Manager Approval',
    createdOn: '2025-04-29',
    lastUpdatedOn: '2025-04-30',
    reviewTypes: [ReviewType.Proposal],
    funds: [
      { id: 3, amount: 1243 },
      { id: 9, amount: 654 },
      { id: 24, amount: 245 },
    ],
    transactionType: 'Purchase Order',
    amount: 135000,
  },
  {
    id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567845',
    controlNo: 'REQ-2025-045',
    vendor: 'Acme Supplies Co.',
    subject: 'Filing Cabinets — Records Management Room',
    status: RequestStatus.Completed,
    currentStep: 'Released',
    createdOn: '2025-04-30',
    lastUpdatedOn: '2025-05-03',
    reviewTypes: [ReviewType.Contract],
    funds: [
      { id: 1, amount: 234 },
      { id: 18, amount: 423 },
      { id: 17, amount: 567 },
    ],
    transactionType: 'Purchase Order',
    amount: 42000,
  },
  {
    id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567846',
    controlNo: 'REQ-2025-046',
    vendor: 'ProHealth Medical Supplies',
    subject: 'Ergonomic Wrist Rests and Mouse Pads — Bulk Order',
    status: RequestStatus.Draft,
    currentStep: 'Requestor Review',
    createdOn: '2025-05-01',
    lastUpdatedOn: '2025-05-01',
    reviewTypes: [ReviewType.Proposal],
    funds: [
      { id: 12, amount: 312 },
      { id: 7, amount: 445 },
      { id: 2, amount: 512 },
    ],
    transactionType: 'Purchase Order',
    amount: 9500,
  },
  {
    id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567847',
    controlNo: 'REQ-2025-047',
    vendor: 'SwiftCourier Logistics',
    subject: 'Same-Day Delivery Service Agreement — Q2',
    status: RequestStatus.UnderReview,
    currentStep: 'Operations Approval',
    createdOn: '2025-05-02',
    lastUpdatedOn: '2025-05-04',
    reviewTypes: [ReviewType.Proposal],
    funds: [
      { id: 14, amount: 445 },
      { id: 6, amount: 1000 },
    ],
    transactionType: 'Service Contract',
    amount: 54000,
  },
  {
    id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567848',
    controlNo: 'REQ-2025-048',
    vendor: 'SafeVault Document Storage',
    subject: 'Secure Shredding Service — Confidential Files',
    status: RequestStatus.Rejected,
    currentStep: 'Compliance Approval',
    createdOn: '2025-05-03',
    lastUpdatedOn: '2025-05-06',
    reviewTypes: [ReviewType.Others],
    funds: [
      { id: 17, amount: 567 },
      { id: 18, amount: 423 },
      { id: 9, amount: 654 },
    ],
    transactionType: 'Service Contract',
    amount: 8000,
  },
  {
    id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567849',
    controlNo: 'REQ-2025-049',
    vendor: 'TechZone Philippines',
    subject: 'Tablet Procurement — Field Operations Team',
    status: RequestStatus.UnderReview,
    currentStep: 'Department Head Approval',
    createdOn: '2025-05-04',
    lastUpdatedOn: '2025-05-05',
    reviewTypes: [ReviewType.Contract],
    funds: [
      { id: 3, amount: 1243 },
      { id: 4, amount: 891 },
      { id: 27, amount: 456 },
    ],
    transactionType: 'Purchase Order',
    amount: 168000,
  },
  {
    id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567850',
    controlNo: 'REQ-2025-050',
    vendor: 'GreenLeaf Catering',
    subject: 'Employee Appreciation Lunch — May',
    status: RequestStatus.Completed,
    currentStep: 'Released',
    createdOn: '2025-05-05',
    lastUpdatedOn: '2025-05-08',
    reviewTypes: [ReviewType.Others],
    funds: [
      { id: 26, amount: 123 },
      { id: 16, amount: 789 },
      { id: 20, amount: 356 },
    ],
    transactionType: 'Service Contract',
    amount: 45000,
  },
  {
    id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567851',
    controlNo: 'REQ-2025-051',
    vendor: 'NetConnect ISP',
    subject: 'Dedicated Leased Line — Data Center',
    status: RequestStatus.Draft,
    currentStep: 'Requestor Review',
    createdOn: '2025-05-06',
    lastUpdatedOn: '2025-05-06',
    reviewTypes: [ReviewType.Contract],
    funds: [
      { id: 3, amount: 1243 },
      { id: 22, amount: 567 },
      { id: 10, amount: 923 },
    ],
    transactionType: 'Service Contract',
    amount: 240000,
  },
  {
    id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567852',
    controlNo: 'REQ-2025-052',
    vendor: 'BrightSpark Electrical',
    subject: 'LED Lighting Retrofit — Warehouse Floor',
    status: RequestStatus.UnderReview,
    currentStep: 'Budget Review',
    createdOn: '2025-05-07',
    lastUpdatedOn: '2025-05-09',
    reviewTypes: [ReviewType.Proposal],
    funds: [
      { id: 5, amount: 678 },
      { id: 10, amount: 923 },
      { id: 25, amount: 178 },
    ],
    transactionType: 'Purchase Order',
    amount: 72000,
  },
  {
    id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567853',
    controlNo: 'REQ-2025-053',
    vendor: 'UrbanFurniture PH',
    subject: 'Standing Desks — Executive Floor',
    status: RequestStatus.Returned,
    currentStep: 'Requestor Review',
    createdOn: '2025-05-08',
    lastUpdatedOn: '2025-05-10',
    reviewTypes: [ReviewType.Proposal],
    funds: [
      { id: 1, amount: 234 },
      { id: 2, amount: 512 },
    ],
    transactionType: 'Purchase Order',
    amount: 128000,
  },
  {
    id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567854',
    controlNo: 'REQ-2025-054',
    vendor: 'ElitePrint Digital',
    subject: 'Annual Report Printing — Board Copies',
    status: RequestStatus.UnderReview,
    currentStep: 'VP Finance Approval',
    createdOn: '2025-05-09',
    lastUpdatedOn: '2025-05-11',
    reviewTypes: [ReviewType.Others],
    funds: [
      { id: 8, amount: 187 },
      { id: 17, amount: 567 },
      { id: 18, amount: 423 },
    ],
    transactionType: 'Purchase Order',
    amount: 38000,
  },
  {
    id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567855',
    controlNo: 'REQ-2025-055',
    vendor: 'PowerSource Electrical',
    subject: 'Solar Inverter Replacement — Rooftop Unit',
    status: RequestStatus.Draft,
    currentStep: 'Requestor Review',
    createdOn: '2025-05-10',
    lastUpdatedOn: '2025-05-10',
    reviewTypes: [ReviewType.Proposal],
    funds: [
      { id: 5, amount: 678 },
      { id: 25, amount: 178 },
      { id: 10, amount: 923 },
    ],
    transactionType: 'Purchase Order',
    amount: 95000,
  },
];

export const mockApprovalActivities = [
  {
    approvalGroupName: "Requestor",
    comments: [
      {
        commenter: "De Marco, Jose",
        comment: "Requesting for external training for the team. The training costs Php10,000.00 for a min of 30pax. Please see provided link for reference.",
        commentedAt: "2024-06-12T09:30:00",
        references: [
          {
            label: 'Training',
            url: 'https://www.google.com',
          },
        ],
      },
      {
        commenter: "Tiongson, Pia",
        comment: "All good for me.",
        commentedAt: "2024-06-12T11:47:00",
        references: [],
      },
    ],
    signatures: [
      {
        name: "De Marco, Jose",
        isSigned: true,
        signedAt: "2024-06-12T12:13:00",
      },
      {
        name: "Tiongson, Pia",
        isSigned: true,
        signedAt: "2024-06-12T17:09:00",
      },
    ],
  },
  {
    approvalGroupName: "Department Head Approval",
    comments: [
      {
        commenter: "Villanueva, Marco",
        comment: "Reviewed the request. Can you confirm whether the training provider is accredited by TESDA or any recognized body? Please attach supporting documentation if available.",
        commentedAt: "2024-06-12T14:20:00",
        references: [],
      },
      {
        commenter: "De Marco, Jose",
        comment: "Hi Sir Marco, the provider is not TESDA-accredited but they are a registered SEC corporation with prior engagements with two of our partner companies. I've added their company profile link under references.",
        commentedAt: "2024-06-12T15:05:00",
        references: [
          {
            label: 'Provider Company Profile',
            url: 'https://www.google.com',
          },
          {
            label: 'Previous Client List',
            url: 'https://www.google.com',
          },
        ],
      },
      {
        commenter: "Villanueva, Marco",
        comment: "Noted. That's acceptable for this type of training. I'll endorse this to Budget Review.",
        commentedAt: "2024-06-13T09:58:00",
        references: [],
      },
    ],
    signatures: [
      {
        name: "Villanueva, Marco",
        isSigned: true,
        signedAt: "2024-06-13T10:45:00",
      },
    ],
  },
  {
    approvalGroupName: "Budget Review",
    comments: [
      {
        commenter: "Reyes, Ana",
        comment: "Checking fund availability. The requested amount of Php300,000.00 (30 pax × Php10,000.00) will be sourced from the Q3 Training and Development fund. Current available balance is Php415,000.00.",
        commentedAt: "2024-06-13T11:10:00",
        references: [
          {
            label: 'Q3 T&D Budget Summary',
            url: 'https://www.google.com',
          },
          {
            label: 'Fund Utilization Policy',
            url: 'https://www.google.com',
          },
        ],
      },
      {
        commenter: "De Marco, Jose",
        comment: "Hi Ma'am Ana, we actually have 32 confirmed participants now. Please let us know if we need to revise the total amount.",
        commentedAt: "2024-06-13T11:48:00",
        references: [],
      },
      {
        commenter: "Reyes, Ana",
        comment: "Yes, please update the request amount to Php320,000.00 to reflect 32 pax. Remaining T&D balance after this will be Php95,000.00. Budget is available — endorsing to Finance.",
        commentedAt: "2024-06-13T13:05:00",
        references: [
          {
            label: 'Budget Request Form',
            url: 'https://www.google.com',
          },
        ],
      },
      {
        commenter: "De Marco, Jose",
        comment: "Understood. Amount has been updated accordingly. Thank you!",
        commentedAt: "2024-06-13T13:31:00",
        references: [],
      },
    ],
    signatures: [
      {
        name: "Reyes, Ana",
        isSigned: true,
        signedAt: "2024-06-13T15:22:00",
      },
      {
        name: "Castillo, Dennis",
        isSigned: true,
        signedAt: "2024-06-14T09:05:00",
      },
    ],
  },
  {
    approvalGroupName: "Finance Approval",
    comments: [
      {
        commenter: "Santos, Lito",
        comment: "Please attach the official quotation from the training provider. We need this for the check voucher preparation.",
        commentedAt: "2024-06-14T14:22:00",
        references: [
          {
            label: 'Accounts Payable Guidelines',
            url: 'https://www.google.com',
          },
          {
            label: 'Check Voucher Template',
            url: 'https://www.google.com',
          },
        ],
      },
      {
        commenter: "De Marco, Jose",
        comment: "Hi Sir Lito, attached is the formal quotation under references. The training is scheduled for July 5–6, 2024.",
        commentedAt: "2024-06-14T15:03:00",
        references: [
          {
            label: 'Official Quotation',
            url: 'https://www.google.com',
          },
          {
            label: 'Training Schedule',
            url: 'https://www.google.com',
          },
        ],
      },
      {
        commenter: "Santos, Lito",
        comment: "Received. One more — are meals and accommodations covered in the Php10,000 rate, or are those billed separately?",
        commentedAt: "2024-06-14T16:10:00",
        references: [],
      },
      {
        commenter: "De Marco, Jose",
        comment: "The rate is inclusive of training materials and AM/PM snacks. Lunch is separate and will be charged to the event budget, not this request.",
        commentedAt: "2024-06-14T16:44:00",
        references: [],
      },
      {
        commenter: "Santos, Lito",
        comment: "Noted and documented. Financials are in order. Forwarding to Finance Head for final sign-off.",
        commentedAt: "2024-06-17T10:55:00",
        references: [],
      },
    ],
    signatures: [
      {
        name: "Santos, Lito",
        isSigned: true,
        signedAt: "2024-06-17T11:30:00",
      },
      {
        name: "Cruz, Maribel",
        isSigned: true,
        signedAt: "2024-06-17T16:55:00",
      },
    ],
  },
  {
    approvalGroupName: "VP Operations Approval",
    comments: [
      {
        commenter: "Alcantara, Roberto",
        comment: "I've reviewed the full endorsement chain. This aligns well with the team's capability roadmap for H2. No objections — approving.",
        commentedAt: "2024-06-18T09:22:00",
        references: [
          {
            label: 'H2 Capability Roadmap',
            url: 'https://www.google.com',
          },
          {
            label: 'HR Training Calendar',
            url: 'https://www.google.com',
          },
        ],
      },
      {
        commenter: "De Marco, Jose",
        comment: "Thank you, Sir Roberto! The team is very much looking forward to this.",
        commentedAt: "2024-06-18T10:14:00",
        references: [],
      },
    ],
    signatures: [
      {
        name: "Alcantara, Roberto",
        isSigned: true,
        signedAt: "2024-06-18T14:15:00",
      },
    ],
  },
  {
    approvalGroupName: "Procurement",
    comments: [
      {
        commenter: "Dizon, Carla",
        comment: "Purchase Order No. PO-2024-1187 has been generated and sent to the supplier. Estimated processing time is 3–5 business days.",
        commentedAt: "2024-06-19T08:35:00",
        references: [
          {
            label: 'PO-2024-1187',
            url: 'https://www.google.com',
          },
          {
            label: 'Supplier Confirmation',
            url: 'https://www.google.com',
          },
        ],
      },
      {
        commenter: "Fuentes, Mark",
        comment: "Check Voucher No. CV-2024-0892 prepared and filed. Payment will be released upon submission of training completion report and official receipt.",
        commentedAt: "2024-06-19T09:02:00",
        references: [
          {
            label: 'CV-2024-0892',
            url: 'https://www.google.com',
          },
          {
            label: 'Payment Release Policy',
            url: 'https://www.google.com',
          },
          {
            label: 'Training Completion Form',
            url: 'https://www.google.com',
          },
        ],
      },
      {
        commenter: "De Marco, Jose",
        comment: "Noted. We'll submit the OR and completion report right after the training on July 6. Thank you everyone!",
        commentedAt: "2024-06-19T09:28:00",
        references: [],
      },
    ],
    signatures: [
      {
        name: "Dizon, Carla",
        isSigned: true,
        signedAt: "2024-06-19T10:00:00",
      },
      {
        name: "Fuentes, Mark",
        isSigned: true,
        signedAt: "2024-06-19T13:48:00",
      },
    ],
  },
  {
    approvalGroupName: "CFO Approval",
    comments: [],
    signatures: [
      {
        name: "Villanueva, Carmen",
        isSigned: false,
        signedAt: null,
      },
    ],
  },
];

export const mockApprovalMatrix = [
  {
    approvalGroupName: "Requestor",
    signatures: ["De Marco, Jose", "Tiongson, Pia"],
  },
  {
    approvalGroupName: "Department Head Approval",
    signatures: ["Villanueva, Marco"],
  },
  {
    approvalGroupName: "Budget Review",
    signatures: ["Reyes, Ana", "Castillo, Dennis"],
  },
  {
    approvalGroupName: "Finance Approval",
    signatures: ["Santos, Lito", "Cruz, Maribel"],
  },
  {
    approvalGroupName: "VP Operations Approval",
    signatures: ["Alcantara, Roberto"],
  },
  {
    approvalGroupName: "Procurement",
    signatures: ["Dizon, Carla", "Fuentes, Mark"],
  },
  {
    approvalGroupName: "CFO Approval",
    signatures: ["Villanueva, Carmen"],
  },
];

export const mockTransactionTypes = [
  { name: 'Purchase Order', children: [] },
  { name: 'Service Contract', children: [] },
  { name: 'Consultancy Agreement', children: [] },
  { name: 'Lease Agreement', children: [] },
  { name: 'Memorandum of Agreement', children: [] },
  { name: 'Request for Quotation', children: [] },
  { name: 'Delivery Order', children: [] },
  { name: 'Work Order', children: [] },
  { name: 'Job Order', children: [] },
  { name: 'Supply Agreement', children: [] },
  {
    name: 'Equipment',
    children: [
      { name: 'Rental', children: [] },
      { name: 'Purchase', children: [] },
      { name: 'Leasing', children: [] },
    ],
  },
  {
    name: 'IT',
    children: [
      { name: 'Software License', children: [] },
      { name: 'SaaS Subscription', children: [] },
      { name: 'Hardware Procurement', children: [] },
      {
        name: 'Maintenance',
        children: [
          { name: 'Software', children: [] },
          { name: 'Hardware', children: [] },
        ],
      },
    ],
  },
  {
    name: 'Infrastructure',
    children: [
      { name: 'Construction', children: [] },
      { name: 'Renovation', children: [] },
      {
        name: 'Repair',
        children: [
          { name: 'Civil', children: [] },
          { name: 'Electrical', children: [] },
          { name: 'Mechanical', children: [] },
        ],
      },
    ],
  },
];

export const mockFunds: Fund[] = [
  { id: 1,  name: 'Furniture'        },
  { id: 2,  name: 'Office Supplies'  },
  { id: 3,  name: 'IT'               },
  { id: 4,  name: 'Hardware'         },
  { id: 5,  name: 'Facilities'       },
  { id: 6,  name: 'Contract'         },
  { id: 7,  name: 'Supplies'         },
  { id: 8,  name: 'Printing'         },
  { id: 9,  name: 'Security'         },
  { id: 10, name: 'Infrastructure'   },
  { id: 11, name: 'Maintenance'      },
  { id: 12, name: 'Health'           },
  { id: 13, name: 'Safety'           },
  { id: 14, name: 'Logistics'        },
  { id: 15, name: 'Legal'            },
  { id: 16, name: 'Human Resources'  },
  { id: 17, name: 'Compliance'       },
  { id: 18, name: 'Records'          },
  { id: 19, name: 'Marketing'        },
  { id: 20, name: 'Events'           },
  { id: 21, name: 'Travel'           },
  { id: 22, name: 'Network'          },
  { id: 23, name: 'Training'         },
  { id: 24, name: 'Licenses'         },
  { id: 25, name: 'Energy'           },
  { id: 26, name: 'Catering'         },
  { id: 27, name: 'Operations'       },
];

export const mockApprovers = [
  {
    id: 'a3f1e2d4-bc56-4789-9a01-2b3c4d5e6f70',
    name: 'Santos, Maria',
  },
  {
    id: 'b4e2f3c5-cd67-489a-ab12-3c4d5e6f7081',
    name: 'Reyes, Juan',
  },
  {
    id: 'c5d3e4b6-de78-49ab-bc23-4d5e6f708192',
    name: 'Cruz, Ana',
  },
  {
    id: 'd6c4f5a7-ef89-4abc-cd34-5e6f70819203',
    name: 'Garcia, Luis',
  },
  {
    id: 'e7b50698-f09a-4bcd-de45-6f7081920314',
    name: 'Torres, Carmen',
  },
  {
    id: 'f8a61709-019b-4cde-ef56-708192031425',
    name: 'Boyle, Charles',
  },
  {
    id: '09b7280a-12ac-4def-f067-819203142536',
    name: 'Holt, Raymond',
  },
  {
    id: '1ac8391b-23bd-4ef0-0178-920314253647',
    name: 'Cooper, Sheldon',
  },
  {
    id: '2bd9402c-34ce-4f01-1289-031425364758',
    name: 'Dalisay, Cardo',
  },
];
